### ISSUE TITLE
The project has few misspelling words

### ISSUE THREAD

**Issue by tandaraelena** [marianzburlea/private-codetap-academy-start#2]
Please correct the word "amzing" to "amazing" 
![Capture](https://user-images.githubusercontent.com/44546169/70389792-15e38600-19bc-11ea-918b-817bfec61c57.JPG)
![Capture2](https://user-images.githubusercontent.com/44546169/70389793-15e38600-19bc-11ea-8419-444f1e5c4a0d.JPG)

**Comment by marianzburlea** [comment]
94f195c3bcbacac8917dcc1a32aa7028c0345c06 closes this issue
